// <auto-generated />
using System;
using CatalogApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogApi.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260325151913_AddAuditingFields")]
    partial class AddAuditingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 3, 25, 15, 19, 12, 311, DateTimeKind.Utc).AddTicks(7338),
                            Description = "High performance laptop",
                            ImageUrl = "",
                            Name = "Laptop",
                            Price = 1299.99m,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2026, 3, 25, 15, 19, 12, 311, DateTimeKind.Utc).AddTicks(7340)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 3, 25, 15, 19, 12, 311, DateTimeKind.Utc).AddTicks(7353),
                            Description = "Latest model smartphone",
                            ImageUrl = "",
                            Name = "Smartphone",
                            Price = 799.99m,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2026, 3, 25, 15, 19, 12, 311, DateTimeKind.Utc).AddTicks(7353)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Furniture",
                            CreatedAt = new DateTime(2026, 3, 25, 15, 19, 12, 311, DateTimeKind.Utc).AddTicks(7355),
                            Description = "Ergonomic office chair",
                            ImageUrl = "",
                            Name = "Desk Chair",
                            Price = 199.99m,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2026, 3, 25, 15, 19, 12, 311, DateTimeKind.Utc).AddTicks(7355)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 3, 25, 15, 19, 12, 311, DateTimeKind.Utc).AddTicks(7357),
                            Description = "27 inch 4K monitor",
                            ImageUrl = "",
                            Name = "Monitor",
                            Price = 349.99m,
                            StockQuantity = 30,
                            UpdatedAt = new DateTime(2026, 3, 25, 15, 19, 12, 311, DateTimeKind.Utc).AddTicks(7358)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
